- hosts: all
  tasks:
  - name: Update all packages to ensure docker can be installed
    apt:
      update_cache: yes
    become: yes
  - name: Install Apache Server
    apt:
      name: apache2
      state: present
    become: yes
  - name: Creates directory for html
    file:
      path: /var/www/michaelwmason95
      state: directory
    become: yes