format_version: 10
pipelines:
  Web_Check:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-28af5dc:
        git: git@github.com:michaelwmason/michaelwmason95.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - Check:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Style:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - install
                command: npm
                working_directory: web
                run_if: passed
            - exec:
                arguments:
                - chown
                - -R
                - go:go
                - node_modules
                command: sudo
                working_directory: web
                run_if: passed
            - exec:
                arguments:
                - run
                - style
                command: npm
                working_directory: web
                run_if: passed
          Lint:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - install
                command: npm
                working_directory: web
                run_if: passed
            - exec:
                arguments:
                - run
                - lint
                command: npm
                working_directory: web
                run_if: passed
          BuildChromiumImage:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - docker
                - build
                - -t
                - chromium
                - .
                command: sudo
                working_directory: web/chromium
                run_if: passed
          RunTests:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - install
                command: npm
                working_directory: web
                run_if: passed
            - exec:
                arguments:
                - run-tests.sh
                command: bash
                working_directory: web
                run_if: passed
            - exec:
                arguments:
                - chown
                - -R
                - go:go
                - node_modules
                command: sudo
                working_directory: web
                run_if: passed
          Cleanup:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - chown
                - -R
                - go:go
                - web
                command: sudo
                run_if: passed
            - exec:
                arguments:
                - rm
                - -rf
                - node_modules
                command: sudo
                working_directory: web
                run_if: passed
