- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  become: yes
- name: Install ca-certificates
  apt:
    name: ca-certificates
    state: present
  become: yes
- name: Install curl
  apt:
    name: curl
    state: present
  become: yes
- name: Install gnupg
  apt:
    name: gnupg
    state: present
  become: yes
- name: Install lsb-release
  apt:
    name: lsb-release
    state: present
  become: yes
- name: Get stats of docker archive key
  become: yes
  stat:
    path: /usr/share/keyrings/docker-archive-keyring.gpg
  register: existing_docker_key
- name: Add Docker’s official GPG key
  shell: |
     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  when: existing_docker_key.stat.exists == False
- name: Setup repository
  shell: |
    echo \
    "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
- name: Update all packages to ensure docker can be installed
  apt:
    update_cache: yes
  become: yes
- name: Install docker-ce
  apt:
    name: docker-ce
    state: present
  become: yes
- name: Install docker-ce-cli
  apt:
    name: docker-ce-cli
    state: present
  become: yes
- name: Install containerd.io
  apt:
    name: containerd.io
    state: present
  become: yes
   