- name: Install Java 11
  apt:
    name: openjdk-11-jre-headless
    state: present
  become: yes
- name: Install GO CD Agent
  apt:
    name: go-agent
    state: present
  become: yes
- name: Ensure GO CD Agent Service is running
  ansible.builtin.systemd:
    state: restarted
    name: go-agent
  become: yes
