- name: Install GO CD Server
  apt:
    name: go-server
    state: present
  become: yes
- name: Ensure GO CD Server Service is running
  ansible.builtin.systemd:
    state: restarted
    name: go-server
  become: yes
 ## As the go user you have to manually run `sudo su - go; ssh -T git@github.com` after adding the public key
 ## to Github. I cannot figure out a way to get this more automated.
