- name: Install acl
  apt:
    name: acl
    state: present
  become: yes
- name: Install GO CD Server
  apt:
    name: go-server
    state: present
  become: yes
- name: Get stats of a file
  become: yes
  become_user: go
  stat:
    path: ~/.ssh/id_ed25519
  register: existing_github_keys
- name: Create new github ssh keys
  become: yes
  become_user: go
  shell: ssh-keygen -t ed25519 -C "michaelwmason95@gmail.com" -P "" -f ~/.ssh/id_ed25519
  when: existing_github_keys.stat.exists == False
- name: Add Github keys to ssh agent
  shell: |
    eval `ssh-agent -s`
    ssh-add ~/.ssh/id_ed25519
  become: yes 
  become_user: go
  when: existing_github_keys.stat.exists == False
- name: Ensure GO CD Server Service is running
  ansible.builtin.systemd:
    state: restarted
    name: go-server
  become: yes
 ## As the go user you have to manually run `sudo su - go; ssh -T git@github.com` after adding the public key
 ## to Github. I cannot figure out a way to get this more automated.
