- name: Install acl
  apt:
    name: acl
    state: present
  become: yes
- name: Install GO CD Server
  apt:
    name: go-server
    state: present
  become: yes
- name: Create new github ssh keys
  become: yes
  become_user: go
  shell: ssh-keygen -t ed25519 -C "michaelwmason95@gmail.com" -P "" -f ~/.ssh/id_ed25519
- name: Add Github keys to ssh agent
  shell: |
    eval `ssh-agent -s`
    ssh-add ~/.ssh/id_ed25519
  become: yes 
  become_user: go
- name: Contact Github to finalize authentication
  become: yes
  become_user: go
  shell: ssh -T git@github.com -o StrictHostKeyChecking=no
- name: Ensure GO CD Server Service is running
  ansible.builtin.systemd:
    state: restarted
    name: go-server
  become: yes
  # https://stackoverflow.com/questions/43171897/how-to-set-up-gocd-to-handle-private-git-repositories-that-use-ssh-keys-for-auth
  # For enabling github access
