- name: Install GO CD Server
  apt:
    name: go-server
    state: present
  become: yes
- name: Ensure GO CD Server Service is running
  ansible.builtin.systemd:
    state: restarted
    name: go-server
