- name: Install GO CD Server
  apt:
    name: go-server
    state: present
  become: yes
- name: Ensure GO CD Server Service is running
  ansible.builtin.systemd:
    state: restarted
    name: go-server
  become: yes
  # https://stackoverflow.com/questions/43171897/how-to-set-up-gocd-to-handle-private-git-repositories-that-use-ssh-keys-for-auth
  # For enabling github access
