- name: Install GO CD Server
  apt:
    name: go-server
    state: present
  become: yes
- name: Copy Github private key
  ansible.builtin.copy:
    src: ~/.ssh/id_ed25519
    dest: ~/.ssh/id_ed25519
  become: yes 
  become_user: go
- name: Copy Github public key
  ansible.builtin.copy:
    src: ~/.ssh/id_ed25519.pub
    dest: ~/.ssh/id_ed25519.pub
  become: yes 
  become_user: go
- name: Add Github keys to ssh agent
  shell: |
    eval `ssh-agent -s`
    ssh-add ~/.ssh/id_ed25519
  become: yes 
  become_user: go
- name: Ensure GO CD Server Service is running
  ansible.builtin.systemd:
    state: restarted
    name: go-server
  become: yes
  # https://stackoverflow.com/questions/43171897/how-to-set-up-gocd-to-handle-private-git-repositories-that-use-ssh-keys-for-auth
  # For enabling github access
